name: sd_flutter_easyloading
description: A clean and lightweight loading/toast widget for Flutter, Easy to use without context, Support iOSã€Android and Web
version: 3.1.4
homepage: https://github.com/nslogx/flutter_easyloading

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
